/**
 * Nebim renk kataloğu.
 *
 * Kaynak: "nebim tüm renkler.xlsx" (Renk Kodu / Renk Açıklaması / Renk hex).
 * Model girişinde renk seçimi için kullanılır. Liste dışı bir renk için
 * formda "Diğer" seçilir ve renk adı elle yazılır.
 *
 * hex alanı çoğu renk için boştur (katalogda tanımlı değil); dolu olanlarda
 * seçicide küçük bir renk noktası gösterilebilir.
 */

export interface RenkKatalogu {
  /** Nebim renk kodu, ör. "570", "RK076". */
  kod: string;
  /** Renk adı, ör. "Lacivert". */
  ad: string;
  /** "#RRGGBB" ya da boş. */
  hex: string;
}

/** "Diğer" seçeneği: listede olmayan renkler için elle giriş. Formda en başta gösterilir. */
export const DIGER_RENK = "Diğer";

/** Katalogdaki tüm renkler (Excel sırasına göre). */
export const RENKLER: RenkKatalogu[] = [
  { kod: "001", ad: "Beyaz", hex: "" },
  { kod: "010", ad: "Ekru", hex: "" },
  { kod: "070", ad: "Vanilya", hex: "" },
  { kod: "080", ad: "Bej", hex: "" },
  { kod: "081", ad: "Vizon", hex: "" },
  { kod: "090", ad: "Grimelanj", hex: "" },
  { kod: "100", ad: "Civciv Sarı", hex: "" },
  { kod: "1000", ad: "Çok Renkli", hex: "" },
  { kod: "1001", ad: "Haki / Bordo / Turuncu / Beyaz", hex: "" },
  { kod: "1002", ad: "Siyah / Gri / Haki / Lacivert", hex: "" },
  { kod: "1003", ad: "Yeşil / Bej / Beyaz / Lacivert", hex: "" },
  { kod: "1004", ad: "Siyah / Grimelanj / Lacivert / Yeşil", hex: "" },
  { kod: "1005", ad: "Mavi / Beyaz / Lacivert / Bordo", hex: "" },
  { kod: "1006", ad: "Beyaz / Yeşil / Siyah / Taş", hex: "" },
  { kod: "1007", ad: "Lacivert / Lacivert / Beyaz / Beyaz", hex: "" },
  { kod: "1008", ad: "Fosil", hex: "" },
  { kod: "1009", ad: "Jetblack", hex: "" },
  { kod: "1010", ad: "Şal Desen", hex: "" },
  { kod: "1011", ad: "Kamuflaj", hex: "" },
  { kod: "1012", ad: "Street", hex: "" },
  { kod: "1013", ad: "Slogan", hex: "" },
  { kod: "1014", ad: "Dünya", hex: "" },
  { kod: "1015", ad: "Desenli", hex: "" },
  { kod: "1016", ad: "Haki / Desenli", hex: "" },
  { kod: "1017", ad: "Ekru / Desenli", hex: "" },
  { kod: "1018", ad: "Lacivert / Desenli", hex: "" },
  { kod: "1019", ad: "Bordo / Desenli", hex: "" },
  { kod: "1020", ad: "Beyaz / Kırmızı", hex: "" },
  { kod: "1021", ad: "Beyaz / Yeşil", hex: "" },
  { kod: "1022", ad: "Beyaz / Desenli", hex: "" },
  { kod: "1023", ad: "Mavi / Desenli", hex: "" },
  { kod: "1024", ad: "Mor / Desenli", hex: "" },
  { kod: "1025", ad: "Yeşil / Desenli", hex: "" },
  { kod: "1026", ad: "Turuncu /Desenli", hex: "" },
  { kod: "1027", ad: "Sarı /Desenli", hex: "" },
  { kod: "1028", ad: "Pembe /Desenli", hex: "" },
  { kod: "1029", ad: "Siyah - Gri", hex: "" },
  { kod: "1030", ad: "Siyah - Yeşil", hex: "" },
  { kod: "1031", ad: "Siyah - Beyaz", hex: "" },
  { kod: "1032", ad: "Vizon - Bej", hex: "" },
  { kod: "1033", ad: "Lacivert / Ekru", hex: "" },
  { kod: "110", ad: "Sarı", hex: "" },
  { kod: "120", ad: "Açık Sarı", hex: "" },
  { kod: "121", ad: "Petrol Mavi/Taş Rengi", hex: "" },
  { kod: "130", ad: "Hardal", hex: "" },
  { kod: "180", ad: "Safran Sarı", hex: "" },
  { kod: "220", ad: "Turuncu", hex: "" },
  { kod: "290", ad: "Nar Çiçeği", hex: "" },
  { kod: "300", ad: "Pembe", hex: "" },
  { kod: "310", ad: "Neon Pembe", hex: "" },
  { kod: "320", ad: "Somon", hex: "" },
  { kod: "330", ad: "Kırmızı", hex: "" },
  { kod: "340", ad: "Kırmızı / Beyaz", hex: "" },
  { kod: "380", ad: "Açık Pembe", hex: "" },
  { kod: "390", ad: "Mürdüm", hex: "" },
  { kod: "401", ad: "Vişne Rengi", hex: "" },
  { kod: "430", ad: "Fuşya", hex: "" },
  { kod: "440", ad: "Mor", hex: "" },
  { kod: "470", ad: "Saks Mavi", hex: "" },
  { kod: "480", ad: "Lila", hex: "" },
  { kod: "500", ad: "Açık Mavi", hex: "" },
  { kod: "510", ad: "Buz Mavi", hex: "" },
  { kod: "520", ad: "Lacivert / Beyaz", hex: "" },
  { kod: "530", ad: "Bordo", hex: "" },
  { kod: "550", ad: "Mavi", hex: "" },
  { kod: "570", ad: "Lacivert", hex: "" },
  { kod: "580", ad: "Koyu Mavi", hex: "" },
  { kod: "590", ad: "Lacivert", hex: "" },
  { kod: "650", ad: "Mint Yeşil", hex: "" },
  { kod: "660", ad: "Turkuaz", hex: "" },
  { kod: "670", ad: "Petrol Yeşili", hex: "" },
  { kod: "700", ad: "Açık Yeşil", hex: "" },
  { kod: "710", ad: "Neon Yeşil", hex: "" },
  { kod: "720", ad: "Lıme Yeşil", hex: "" },
  { kod: "740", ad: "Taş Rengi", hex: "" },
  { kod: "750", ad: "Fıstık Yeşili", hex: "" },
  { kod: "760", ad: "Açık Haki", hex: "" },
  { kod: "770", ad: "Yeşil", hex: "" },
  { kod: "780", ad: "Haki", hex: "" },
  { kod: "790", ad: "Koyu Yeşil", hex: "" },
  { kod: "830", ad: "Kiremit Rengi", hex: "" },
  { kod: "850", ad: "Gri", hex: "" },
  { kod: "851", ad: "Gri / Siyah", hex: "" },
  { kod: "880", ad: "Kahverengi", hex: "" },
  { kod: "881", ad: "Açık Kahverengi Karamel", hex: "" },
  { kod: "890", ad: "Koyu Kahverengi", hex: "" },
  { kod: "900", ad: "Koyu Gri", hex: "" },
  { kod: "910", ad: "Açık Gri", hex: "" },
  { kod: "920", ad: "Karmelanj", hex: "" },
  { kod: "980", ad: "Antrasit", hex: "" },
  { kod: "987", ad: "Mor / Gri / Siyah", hex: "" },
  { kod: "988", ad: "Siyah / Siyah / Beyaz", hex: "" },
  { kod: "989", ad: "Mavi / Yeşil / Siyah", hex: "" },
  { kod: "990", ad: "Siyah", hex: "" },
  { kod: "991", ad: "Siyah/Beyaz", hex: "" },
  { kod: "992", ad: "Siyah - Puantiyeli", hex: "" },
  { kod: "993", ad: "Siyah - Zebra", hex: "" },
  { kod: "994", ad: "Gri / Grimelanj", hex: "" },
  { kod: "995", ad: "Mavi / Turuncu", hex: "" },
  { kod: "996", ad: "Yeşil / Pembe / Beyaz", hex: "" },
  { kod: "997", ad: "Mavi / Turuncu / Beyaz", hex: "" },
  { kod: "998", ad: "Haki / Siyah / Grimelanj", hex: "" },
  { kod: "999", ad: "Bej / Tarçın / haki", hex: "" },
  { kod: "RK.168", ad: "Siyah / Lacivert / Grimelanj", hex: "" },
  { kod: "RK.204", ad: "Ekru Çizgili", hex: "" },
  { kod: "RK.214", ad: "Koyu Grimelanj", hex: "" },
  { kod: "RK.215", ad: "Grimelanj Çizgili", hex: "" },
  { kod: "RK001", ad: "Şampanya Rengi", hex: "" },
  { kod: "RK002", ad: "İndigo", hex: "" },
  { kod: "RK003", ad: "Bej / Desenli", hex: "" },
  { kod: "RK004", ad: "Acı Kahve", hex: "" },
  { kod: "RK005", ad: "Açık Bej", hex: "" },
  { kod: "RK006", ad: "Füme", hex: "" },
  { kod: "RK007", ad: "Gri / Beyaz", hex: "" },
  { kod: "RK008", ad: "Antrasit / Çizgili", hex: "" },
  { kod: "RK009", ad: "Taba", hex: "" },
  { kod: "RK010", ad: "Açık Kahverengi", hex: "" },
  { kod: "RK011", ad: "Lacivert/Haki", hex: "" },
  { kod: "RK012", ad: "Siyah - Antrasit", hex: "" },
  { kod: "RK013", ad: "Siyah - Saks", hex: "" },
  { kod: "RK014", ad: "Badem Yeşili", hex: "" },
  { kod: "RK015", ad: "Beyaz - Vizon", hex: "" },
  { kod: "RK016", ad: "Beyaz - Gri", hex: "" },
  { kod: "RK017", ad: "Beyaz - Antrasit", hex: "" },
  { kod: "RK018", ad: "Bej - Beyaz", hex: "" },
  { kod: "RK019", ad: "Pudra", hex: "" },
  { kod: "RK020", ad: "Camel", hex: "" },
  { kod: "RK021", ad: "Mavi / Ekru", hex: "" },
  { kod: "RK022", ad: "Mavi / Beyaz", hex: "" },
  { kod: "RK023", ad: "Petrol Mavisi", hex: "" },
  { kod: "RK024", ad: "Çağla Yeşili", hex: "" },
  { kod: "RK025", ad: "Kahverengi / Siyah", hex: "" },
  { kod: "RK026", ad: "Açık Lila", hex: "" },
  { kod: "RK027", ad: "Lacivert - Pembe - Beyaz", hex: "" },
  { kod: "RK028", ad: "Siyah - Beyaz - Gri", hex: "" },
  { kod: "RK029", ad: "Antrasit - Siyah - Beyaz", hex: "" },
  { kod: "RK030", ad: "Mint / YavruAğzı / Beyaz", hex: "" },
  { kod: "RK031", ad: "Mürdüm / Gri / Beyaz", hex: "" },
  { kod: "RK032", ad: "Fıstık Yeşili / Siyah / Beyaz", hex: "" },
  { kod: "RK033", ad: "Mint - Grimelanj", hex: "" },
  { kod: "RK034", ad: "Kiremit - Grimelanj", hex: "" },
  { kod: "RK035", ad: "Mor - Yeşil", hex: "" },
  { kod: "RK036", ad: "Mor Çizgili - Bordo", hex: "" },
  { kod: "RK037", ad: "Yavruağzı Çizgili -  Gri", hex: "" },
  { kod: "RK038", ad: "Beyaz-Gri Çizgili", hex: "" },
  { kod: "RK039", ad: "Yavruağzı-Bordo Çizgili", hex: "" },
  { kod: "RK040", ad: "Yeşil-Mor Çizgili", hex: "" },
  { kod: "RK041", ad: "Benetton Yeşili", hex: "" },
  { kod: "RK042", ad: "Mürdüm - Beyaz", hex: "" },
  { kod: "RK043", ad: "Yeşil - Grimelanj", hex: "" },
  { kod: "RK044", ad: "Fıstık yeşili - Siyah", hex: "" },
  { kod: "RK045", ad: "Kırmızı - Lacivert", hex: "" },
  { kod: "RK046", ad: "Yavruağzı", hex: "" },
  { kod: "RK047", ad: "Laci/Bej/Byz", hex: "" },
  { kod: "RK048", ad: "Syh/Byz/Saks", hex: "" },
  { kod: "RK049", ad: "Byz/Gri/Laci", hex: "" },
  { kod: "RK050", ad: "Bej/Syh/Byz", hex: "" },
  { kod: "RK051", ad: "Laci/Ekru/Pmb", hex: "" },
  { kod: "RK052", ad: "Trncu/Bej", hex: "" },
  { kod: "RK053", ad: "Gri/Ekru", hex: "" },
  { kod: "RK054", ad: "Syh/Grmj/Byz", hex: "" },
  { kod: "RK055", ad: "Pmb/ Gri/ Vzn/ Byz", hex: "" },
  { kod: "RK056", ad: "Şeftali", hex: "" },
  { kod: "RK057", ad: "Ekru/AçıkGri/Antrasit", hex: "" },
  { kod: "RK058", ad: "Ekru/Yeşil/Lacivert", hex: "" },
  { kod: "RK059", ad: "Ekru/Bej/Siyah", hex: "" },
  { kod: "RK060", ad: "Ekru/Gri", hex: "" },
  { kod: "RK061", ad: "Ekru/Kırmızı", hex: "" },
  { kod: "RK062", ad: "Beyaz/Navy", hex: "" },
  { kod: "rk063", ad: "Navy/Beyaz", hex: "" },
  { kod: "RK064", ad: "Ekru/Mavi", hex: "" },
  { kod: "RK065", ad: "Mavi - Sarı", hex: "" },
  { kod: "RK066", ad: "Lime", hex: "" },
  { kod: "RK067", ad: "Siyah - Mavi", hex: "" },
  { kod: "RK068", ad: "Yeşil - Sarı", hex: "" },
  { kod: "RK069", ad: "Lacivert - Pembe", hex: "" },
  { kod: "RK070", ad: "Pembe - Yeşil", hex: "" },
  { kod: "RK071", ad: "Kırmızı - Siyah - Pembe", hex: "" },
  { kod: "RK072", ad: "Mandalina", hex: "" },
  { kod: "RK073", ad: "Sarı-Mavi / Desenli", hex: "" },
  { kod: "RK074", ad: "Koyu Pembe", hex: "" },
  { kod: "RK075", ad: "Kırmızı - Pembe", hex: "" },
  { kod: "RK076", ad: "Navy", hex: "" },
  { kod: "RK077", ad: "Yeşil Su Desenli", hex: "" },
  { kod: "RK078", ad: "S.Mavis/Gri/Beyaz", hex: "" },
  { kod: "RK079", ad: "Asker Yeşili", hex: "" },
  { kod: "RK080", ad: "Parlament Mavi", hex: "" },
  { kod: "RK081", ad: "Kırmızı - Siyah", hex: "" },
  { kod: "RK082", ad: "Krem", hex: "" },
  { kod: "RK083", ad: "Leopar Desenli", hex: "" },
  { kod: "RK084", ad: "Gül Kurusu", hex: "" },
  { kod: "RK085", ad: "Grimelanj - Siyah", hex: "" },
  { kod: "RK086", ad: "Grimelanj - Sarı", hex: "" },
  { kod: "RK087", ad: "Vizon - Lacivert", hex: "" },
  { kod: "RK088", ad: "Grimelanj - Beyaz", hex: "" },
  { kod: "RK089", ad: "Koyu Antrasit", hex: "" },
  { kod: "RK090", ad: "Beyaz - Kırmızı - Lacivert", hex: "" },
  { kod: "RK091", ad: "Beyaz - Grimelanj - Lacivert", hex: "" },
  { kod: "RK092", ad: "Beyaz - Grimelanj - Açık Yeşil", hex: "" },
  { kod: "RK093", ad: "Koyu Mor", hex: "" },
  { kod: "RK094", ad: "Yeşil- Çizgili", hex: "" },
  { kod: "RK095", ad: "Beyaz - Kiraz Baskılı", hex: "" },
  { kod: "RK096", ad: "Beyaz - Pembe baskılı", hex: "" },
  { kod: "RK097", ad: "Beyaz - Kırmızı Baskılı", hex: "" },
  { kod: "RK098", ad: "Beyaz - Lacivert Baskılı", hex: "" },
  { kod: "RK099", ad: "Beyaz - Siyah Baskılı", hex: "" },
  { kod: "RK100", ad: "Siyah - Beyaz - Grimelanj", hex: "" },
  { kod: "RK101", ad: "Beyaz/Grimelanj/Pembe/Lacivert/Gri", hex: "" },
  { kod: "RK102", ad: "Beyaz/Siyah/AçıkYeşil/Gri/Lcvrt", hex: "" },
  { kod: "RK103", ad: "Bordo/Lcvrt/Gri", hex: "" },
  { kod: "RK104", ad: "İnd/AYeşil/AGri", hex: "" },
  { kod: "RK105", ad: "Vnly/KYeşil/Krmt", hex: "" },
  { kod: "RK106", ad: "Siyah / Grimelanj", hex: "" },
  { kod: "RK107", ad: "Siyah/Sarı", hex: "" },
  { kod: "RK108", ad: "Syh-Grmj/Grmj-Syh", hex: "" },
  { kod: "RK109", ad: "Grmj-Syh/Syh-Grmj", hex: "" },
  { kod: "RK110", ad: "Lacivert/Haki/Turuncu", hex: "" },
  { kod: "RK111", ad: "Koyu Bej", hex: "" },
  { kod: "RK112", ad: "Siyah/Ekru", hex: "" },
  { kod: "RK113", ad: "Lacivert-Yeşil", hex: "" },
  { kod: "RK114", ad: "Yılan Desenli", hex: "" },
  { kod: "RK115", ad: "Vintage Mavi", hex: "" },
  { kod: "RK116", ad: "Ekru-Acı Kahve", hex: "" },
  { kod: "RK117", ad: "Siyah-Granit Yeşili", hex: "" },
  { kod: "RK118", ad: "Acı kahve-Taş Rengi", hex: "" },
  { kod: "RK119", ad: "Siyah-Granit Yeşili", hex: "" },
  { kod: "RK120", ad: "Petrol Mavi/Ekru", hex: "" },
  { kod: "RK121", ad: "Petrol Mavi/Taş Rengi", hex: "" },
  { kod: "RK122", ad: "Granit Yeşili", hex: "" },
  { kod: "RK123", ad: "Grimelanj/Petrol Mavi", hex: "" },
  { kod: "RK124", ad: "Ekru/Siyah", hex: "" },
  { kod: "RK125", ad: "Zen Mavisi", hex: "" },
  { kod: "RK126", ad: "Ekru/Lacivert", hex: "" },
  { kod: "RK127", ad: "Şeker Pembesi", hex: "" },
  { kod: "RK128", ad: "Açık Mürdüm", hex: "" },
  { kod: "RK129", ad: "Acı Kahve/Ekru", hex: "" },
  { kod: "RK130", ad: "Koyu Kahverengi/Ekru", hex: "" },
  { kod: "RK131", ad: "Siyah/Açık Yeşil", hex: "" },
  { kod: "RK132", ad: "Siyah/Açık Mürdüm", hex: "" },
  { kod: "RK133", ad: "Ekru/Açık Yeşil", hex: "" },
  { kod: "RK134", ad: "Ekru/Kahverengi", hex: "" },
  { kod: "RK135", ad: "Ekru/Vişne Rengi", hex: "" },
  { kod: "RK136", ad: "Siyah/Zen Mavisi", hex: "" },
  { kod: "RK137", ad: "Grimelanj/Vişne", hex: "" },
  { kod: "RK138", ad: "Grimelanj/Lacivert", hex: "" },
  { kod: "RK139", ad: "Şeker Pembe/Ekru", hex: "" },
  { kod: "RK140", ad: "Antrasit/Beyaz/Beyaz", hex: "" },
  { kod: "RK141", ad: "Siyah/Beyaz/Lacivert", hex: "" },
  { kod: "RK142", ad: "Siyah/Gri/Antrasit", hex: "" },
  { kod: "RK143", ad: "Siyah/Beyaz/Antrasit", hex: "" },
  { kod: "RK144", ad: "Wild Vintage", hex: "" },
  { kod: "RK145", ad: "Orta Mavi", hex: "" },
  { kod: "RK146", ad: "Parlak Siyah", hex: "" },
  { kod: "RK147", ad: "Mat Siyah", hex: "" },
  { kod: "RK148", ad: "Siyah Desenli", hex: "" },
  { kod: "RK149", ad: "Mavi / Taş Rengi", hex: "" },
  { kod: "RK150", ad: "Siyah-Beyaz / Desenli", hex: "" },
  { kod: "RK151", ad: "Siyah/Gül Kurusu", hex: "" },
  { kod: "RK152", ad: "Siyah/Fıstık Yeşili", hex: "" },
  { kod: "RK153", ad: "Kolej Yeşili", hex: "" },
  { kod: "RK154", ad: "Cow Desenli", hex: "" },
  { kod: "RK155", ad: "Zebra Desenli", hex: "" },
  { kod: "RK156", ad: "Tiger Desenli", hex: "" },
  { kod: "RK157", ad: "Kırmızı / Mavi", hex: "" },
  { kod: "RK158", ad: "Beyaz / Fıstık Yeşili", hex: "" },
  { kod: "RK159", ad: "Turkuaz / Turuncu / Beyaz", hex: "" },
  { kod: "RK160", ad: "Kahverengi / Mavi", hex: "" },
  { kod: "RK161", ad: "Beyaz / Sarı", hex: "" },
  { kod: "RK162", ad: "Beyaz / Pembe", hex: "" },
  { kod: "RK163", ad: "Beyaz / Mavi / Sarı", hex: "" },
  { kod: "RK164", ad: "Ekru/Fıstık Yeşili", hex: "" },
  { kod: "RK165", ad: "Haki / Ekru", hex: "" },
  { kod: "RK166", ad: "Pembe Melanj", hex: "" },
  { kod: "RK167", ad: "Siyah / Siyah / Siyah", hex: "" },
  { kod: "RK168", ad: "Beyaz-Mavi Çizgili", hex: "" },
  { kod: "RK169", ad: "Beyaz-Yeşil Çizgili", hex: "" },
  { kod: "RK170", ad: "Koyu Turkuaz", hex: "" },
  { kod: "RK171", ad: "Bordo - Lacivert", hex: "" },
  { kod: "RK172", ad: "Grimelanj - Bej", hex: "" },
  { kod: "RK173", ad: "Koyu Vizon", hex: "" },
  { kod: "RK174", ad: "Koyu Lacivert", hex: "" },
  { kod: "RK175", ad: "Koyu Haki", hex: "" },
  { kod: "RK176", ad: "Siyah-Çizgili", hex: "" },
  { kod: "RK177", ad: "Bordo-Çizgili", hex: "" },
  { kod: "RK178", ad: "Lacivert-Çizgili", hex: "" },
  { kod: "RK179", ad: "Mocha", hex: "" },
  { kod: "RK180", ad: "Mocha-Bej", hex: "" },
  { kod: "RK181", ad: "Siyah-Leopar Desenli", hex: "" },
  { kod: "RK182", ad: "Kahverengi-Çiçek Desenli", hex: "" },
  { kod: "RK183", ad: "Koyu Bordo", hex: "" },
  { kod: "RK184", ad: "Siyah-Kristal Taşlı", hex: "" },
  { kod: "RK185", ad: "Antrasitmelanj", hex: "" },
  { kod: "RK186", ad: "Kahvemelanj", hex: "" },
  { kod: "RK187", ad: "Beyaz Taşlı", hex: "" },
  { kod: "RK188", ad: "Bej Taşlı", hex: "" },
  { kod: "RK189", ad: "Bordo Taşlı", hex: "" },
  { kod: "RK190", ad: "Haki Taşlı", hex: "" },
  { kod: "RK191", ad: "Siyah Taşlı", hex: "" },
  { kod: "RK192", ad: "Açık Vizon", hex: "" },
  { kod: "RK193", ad: "Lacivert - Ekru - Bordo", hex: "" },
  { kod: "RK194", ad: "Kahverengi - Füme - Ekru", hex: "" },
  { kod: "RK195", ad: "Yeşil - Ekru", hex: "" },
  { kod: "RK196", ad: "Koyu Sarı", hex: "" },
  { kod: "RK197", ad: "Beyaz - Siyah", hex: "" },
  { kod: "RK198", ad: "Çiçek Desenli", hex: "" },
  { kod: "RK199", ad: "Grimelanj - Pembe", hex: "" },
  { kod: "RK200", ad: "Kırmızı Çizgili", hex: "" },
  { kod: "RK201", ad: "Mavi Çizgili", hex: "" },
  { kod: "RK202", ad: "Sarı Çizgili", hex: "" },
  { kod: "RK203", ad: "Pembe Çizgili", hex: "" },
  { kod: "RK205", ad: "Kahverengi Çizgili", hex: "" },
  { kod: "RK206", ad: "Kırmızı Baskılı", hex: "" },
  { kod: "RK207", ad: "Sarı Baskılı", hex: "" },
  { kod: "RK208", ad: "Pembe Baskılı", hex: "" },
  { kod: "RK209", ad: "Ekru Baskılı", hex: "" },
  { kod: "RK210", ad: "Fuşya/Pembe", hex: "" },
  { kod: "RK211", ad: "Fuşya Çizgili", hex: "" },
  { kod: "RK212", ad: "Mor Çizgili", hex: "" },
  { kod: "RK213", ad: "Koyu Fuşya", hex: "" },
  { kod: "RK216", ad: "Bej Çizgili", hex: "" },
  { kod: "RK217", ad: "Vizon Çizgili", hex: "" },
  { kod: "RK218", ad: "Ekru Bordo Çizgili", hex: "" },
  { kod: "RK219", ad: "Parlament Mavi Çizgili", hex: "" },
  { kod: "RK220", ad: "Açık Grimelanj", hex: "" },
  { kod: "RK221", ad: "Kahverengi-Mavi-Beyaz", hex: "" },
  { kod: "RK222", ad: "K.Vizon/Syh/Byz", hex: "" },
  { kod: "RK223", ad: "K.Yeşil/Bej/Lcvrt", hex: "" },
  { kod: "RK224", ad: "Mavi/Kahverengi Çizgili", hex: "" },
  { kod: "RK225", ad: "Pembe-Siyah-Beyaz Çizgili", hex: "" },
  { kod: "RK226", ad: "Bordo-Pembe-Ekru Çizgili", hex: "" },
  { kod: "RK227", ad: "Pembe-A.Pembe Çizgili", hex: "" },
  { kod: "RK228", ad: "Mavi-Siyah-Beyaz Çizgili", hex: "" },
  { kod: "RK229", ad: "Çikolata Kahve", hex: "" },
  { kod: "RK230", ad: "Karamel", hex: "" },
  { kod: "RK231", ad: "Gri - Pembe", hex: "" },
];
